version: "3.7"

services:

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: on-failure:10
    ports:
      - ${HTTP_PORT:-9091}:80
    depends_on:
      - nextcloud_db
      - nextcloud_redis
    links:
      - nextcloud_db
      - nextcloud_redis
    environment:
      NEXTCLOUD_ADMIN_USERNAME: ${ADMIN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${VIRTUAL_HOST}
      REDIS_HOST: nextcloud_redis
      POSTGRES_HOST: nextcloud_db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./html}/html:/var/www/html
  
  nextcloud_db:
    image: postgres:12-alpine
    container_name: nextcloud_db
    restart: on-failure:10
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./postgres/data}/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: nextcloud_db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    sysctls:
      net.core.somaxconn: 4096
    restart: on-failure:10
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./redis}/redis:/var/lib/redis

networks:
  default:
    external:
      name: ${PROXY_NETWORK}
