version: "3.7"

services:

  nextcloud:
    image: nextcloud
    name: nextcloud
    restart: on-failure:10
    ports:
      - ${HTTP_PORT}:80
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      NEXTCLOUD_ADMIN_USERNAME: ${ADMIN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: www.${VIRTUAL_HOST} ${VIRTUAL_HOST}
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      VIRTUAL_HOST: www.${VIRTUAL_HOST},${VIRTUAL_HOST}
      LETSENCRYPT_HOST: www.${VIRTUAL_HOST},${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_TEST: "true"
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./html}/html:/var/www/html
  
  db:
    image: postgres:12-alpine
    name: nextcloud_db
    restart: on-failure:10
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./postgres/data}/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: redis:alpine
    name: nextcloud_redis
    restart: on-failure:10
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./redis}/redis:/var/lib/redis

networks:
  default:
    external:
      name: ${PROXY_NETWORK}
