version: "3.7"

services:

  nextcloud:
    image: nextcloud
    restart: unless-stopped
    expose:
      - ${HTTP_PORT}
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      NEXTCLOUD_ADMIN_USERNAME: ${ADMIN_USERNAME}
      NEXTCLOUD_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_HOST: redis
      VIRTUAL_HOST: www.${VIRTUAL_HOST},${VIRTUAL_HOST}
      LETSENCRYPT_HOST: www.${VIRTUAL_HOST},${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      LETSENCRYPT_TEST: "true"
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./html}/html:/var/www/html
  
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./postgres/data}/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      REDIS_DATABASES: 1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${NEXTCLOUD_FILES_PATH:-./redis}/redis:/var/lib/redis

networks:
  default:
    external:
      name: ${PROXY_NETWORK}
